import PDFDocument from "pdfkit";

import { Response } from "express";

export const generateQuestionPaperPDF = (
  generatedPaper: any,

  assignment: any,

  res: Response,
) => {
  // create a new PDF document
  const doc = new PDFDocument({
    margin: 50,

    size: "A4",
  });
  // set response headers for PDF download
  res.setHeader("Content-Type", "application/pdf");

  res.setHeader(
    "Content-Disposition",

    `attachment; filename=question-paper-${assignment._id}.pdf`,
  );

  doc.pipe(res);
  // header section
  doc
    .fontSize(20)
    .font("Helvetica-Bold")
    .text(
      assignment.schoolName || "VedaAI School",

      {
        align: "center",
      },
    );

  doc.moveDown(0.5);

  doc
    .fontSize(16)
    .font("Helvetica")
    .text(
      assignment.title || "Question Paper",

      {
        align: "center",
      },
    );

  doc.moveDown(0.5);

  doc.fontSize(11).text(`Subject: ${assignment.subject || "N/A"}`, {
    align: "left",
  });

  doc.text(`Class: ${assignment.className || "N/A"}`);

  doc.text(`Due Date: ${assignment.dueDate || "N/A"}`);

  doc.moveDown();
  // Student Information Section
  doc.font("Helvetica-Bold").fontSize(12).text("Student Information");

  doc.moveDown(0.5);

  doc.font("Helvetica").text("Name: ________________________________");

  doc.moveDown(0.5);

  doc.text("Roll Number: _________________________");

  doc.moveDown(0.5);

  doc.text("Section: ______________________________");

  doc.moveDown(1.5);
  // Instructions
  if (assignment.instructions) {
    doc.font("Helvetica-Bold").text("Instructions");

    doc.moveDown(0.5);

    doc.font("Helvetica").text(assignment.instructions);

    doc.moveDown();
  }
  // Sections and Questions
  generatedPaper.sections.forEach((section: any, sectionIndex: number) => {
    // section header with underline
    doc.fontSize(15).font("Helvetica-Bold").text(section.title, {
      underline: true,
    });

    doc.moveDown(0.5);
    // Section instructions
    doc
      .fontSize(11)
      .font("Helvetica")
      .text(section.instruction || "Attempt all questions.");

    doc.moveDown();
    // Questions
    section.questions.forEach((question: any, questionIndex: number) => {
      // Question text
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text(`${questionIndex + 1}. ${question.questionText}`);

      doc.moveDown(0.3);
      // Options for MCQs
      if (question.type === "mcq" && question.options?.length) {
        question.options.forEach((option: string, optionIndex: number) => {
          doc
            .fontSize(11)
            .font("Helvetica")
            .text(`${String.fromCharCode(65 + optionIndex)}. ${option}`, {
              indent: 20,
            });
        });

        doc.moveDown(0.5);
      }
      // Difficulty badge
      const difficulty = (question.difficulty || "medium").toUpperCase();

      doc.fontSize(10).font("Helvetica-Oblique").text(`[ ${difficulty} ]`);
      // Marks
      doc.fontSize(10).font("Helvetica").text(`Marks: ${question.marks}`);
      // divider line
      doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor("#cccccc").stroke();

      doc.moveDown();
    });

    doc.moveDown(1.5);
  });
  // // Footer
  doc.moveDown();

  doc.fontSize(10).fillColor("gray").text(
    "Generated by VedaAI",

    {
      align: "center",
    },
  );
  // finalize PDF and end the stream
  doc.end();
};
